#!/usr/bin/env python3
"""Generate an integer NTC divider-ratio/temperature table from sensors.h."""
import argparse
import math
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def read_constant(text, name):
    match = re.search(
        rf"^#define\s+{re.escape(name)}\s+\(?\s*([+-]?\d+)[uUlL]*\s*\)?\s*$",
        text, re.MULTILINE)
    if not match:
        raise ValueError(f"{name} must be an integer literal #define")
    return int(match.group(1))


def generate(config):
    text = config.read_text()
    r_nominal = read_constant(text, "THERMISTOR_NOMINAL_RESISTANCE_OHM")
    t_nominal = read_constant(text, "THERMISTOR_NOMINAL_TEMP_MDEGC")
    beta = read_constant(text, "THERMISTOR_BETA_K")
    r_bottom = read_constant(text, "THERMISTOR_DIVIDER_BOTTOM_OHM")
    scale = read_constant(text, "THERMISTOR_LUT_RATIO_SCALE")
    lower = read_constant(text, "THERMISTOR_LUT_MIN_TEMP_MDEGC")
    upper = read_constant(text, "THERMISTOR_LUT_MAX_TEMP_MDEGC")
    step = read_constant(text, "THERMISTOR_LUT_STEP_MDEGC")
    if step <= 0:
        raise ValueError("table step must be positive")
    if min(r_nominal, beta, r_bottom, scale) <= 0:
        raise ValueError("resistances, beta and ratio scale must be positive")
    if lower >= upper or (upper - lower) % step:
        raise ValueError("temperature bounds must ascend and span whole steps")
    if min(lower, t_nominal) <= -273150:
        raise ValueError("temperatures must be above absolute zero")
    if scale > 0xFFFFFFFF or lower < -0x80000000 or upper > 0x7FFFFFFF:
        raise ValueError("table values must fit uint32_t/int32_t")

    entries = []
    nominal_kelvin = t_nominal / 1000 + 273.15
    for temperature in range(lower, upper + 1, step):
        kelvin = temperature / 1000 + 273.15
        resistance = r_nominal * math.exp(beta * (1 / kelvin - 1 / nominal_kelvin))
        ratio = round(scale * r_bottom / (resistance + r_bottom))
        if not 0 < ratio < scale or (entries and ratio <= entries[-1][0]):
            raise ValueError("rounded ratios must be distinct, ascending and within scale")
        entries.append((ratio, temperature))

    lines = [
        "/* Generated by scripts/generate_thermistor_lut.py; do not edit manually. */",
        "/* Thermistor upper leg, fixed resistor lower leg; supply is battery voltage. */",
        f"/* Model: R={r_nominal} ohm at {t_nominal} mdegC, beta={beta} K, bottom={r_bottom} ohm. */",
        "#ifndef USER_THERMISTOR_LUT_H", "#define USER_THERMISTOR_LUT_H", "",
        "#include <stdint.h>", '#include "sensors.h"', "",
        f"#define THERMISTOR_LUT_ENTRY_COUNT {len(entries)}U", "",
        "/* Lookup key = Vinput / Vbattery * THERMISTOR_LUT_RATIO_SCALE.",
        " * Use reconstructed battery voltage, not its divided ADC input voltage.",
        " * Normalize ADC readings first; use wide intermediates for integer math.",
        " * Interpolate between adjacent entries; invalid/out-of-range readings",
        " * need handling by future sensor/heater code. No runtime float is needed. */",
        "typedef struct {", "    uint32_t divider_ratio_scaled;",
        "    int32_t temperature_mdegc;", "} thermistor_lut_entry_t;", "",
        "static const thermistor_lut_entry_t thermistor_lut[THERMISTOR_LUT_ENTRY_COUNT] = {",
    ]
    lines += [f"    {{ {ratio}U, {temperature}L }}," for ratio, temperature in entries]
    lines += ["};", "", "#endif /* USER_THERMISTOR_LUT_H */", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=ROOT / "User/Inc/sensors.h")
    parser.add_argument("--output", type=Path, default=ROOT / "User/Inc/thermistor_lut.h")
    args = parser.parse_args()
    try:
        header = generate(args.config)
        args.output.write_text(header)
    except (OSError, ValueError, OverflowError) as error:
        parser.exit(1, f"Thermistor table generation failed: {error}\n")
    print(f"Generated {args.output}")


if __name__ == "__main__":
    main()
