/* Generated by scripts/generate_thermistor_lut.py; do not edit manually. */
/* Thermistor upper leg, fixed resistor lower leg; supply is battery voltage. */
/* Model: R=10000 ohm at 25000 mdegC, beta=3435 K, bottom=4120 ohm. */
#ifndef USER_THERMISTOR_LUT_H
#define USER_THERMISTOR_LUT_H

#include <stdint.h>
#include "sensors.h"

#define THERMISTOR_LUT_ENTRY_COUNT 101U

/* Lookup key = Vinput / Vbattery * THERMISTOR_LUT_RATIO_SCALE.
 * Use reconstructed battery voltage, not its divided ADC input voltage.
 * Normalize ADC readings first; use wide intermediates for integer math.
 * Interpolate between adjacent entries; invalid/out-of-range readings
 * need handling by future sensor/heater code. No runtime float is needed. */
typedef struct {
    uint32_t divider_ratio_scaled;
    int32_t temperature_mdegc;
} thermistor_lut_entry_t;

static const thermistor_lut_entry_t thermistor_lut[THERMISTOR_LUT_ENTRY_COUNT] = {
    { 50464U, -20000L },
    { 53084U, -19000L },
    { 55811U, -18000L },
    { 58646U, -17000L },
    { 61592U, -16000L },
    { 64652U, -15000L },
    { 67827U, -14000L },
    { 71120U, -13000L },
    { 74534U, -12000L },
    { 78069U, -11000L },
    { 81729U, -10000L },
    { 85516U, -9000L },
    { 89430U, -8000L },
    { 93474U, -7000L },
    { 97648U, -6000L },
    { 101956U, -5000L },
    { 106397U, -4000L },
    { 110973U, -3000L },
    { 115684U, -2000L },
    { 120532U, -1000L },
    { 125517U, 0L },
    { 130639U, 1000L },
    { 135898U, 2000L },
    { 141295U, 3000L },
    { 146828U, 4000L },
    { 152499U, 5000L },
    { 158305U, 6000L },
    { 164245U, 7000L },
    { 170320U, 8000L },
    { 176526U, 9000L },
    { 182864U, 10000L },
    { 189330U, 11000L },
    { 195922U, 12000L },
    { 202639U, 13000L },
    { 209478U, 14000L },
    { 216436U, 15000L },
    { 223509U, 16000L },
    { 230695U, 17000L },
    { 237991U, 18000L },
    { 245391U, 19000L },
    { 252894U, 20000L },
    { 260494U, 21000L },
    { 268188U, 22000L },
    { 275971U, 23000L },
    { 283838U, 24000L },
    { 291785U, 25000L },
    { 299807U, 26000L },
    { 307898U, 27000L },
    { 316055U, 28000L },
    { 324271U, 29000L },
    { 332542U, 30000L },
    { 340862U, 31000L },
    { 349226U, 32000L },
    { 357628U, 33000L },
    { 366062U, 34000L },
    { 374525U, 35000L },
    { 383009U, 36000L },
    { 391509U, 37000L },
    { 400021U, 38000L },
    { 408539U, 39000L },
    { 417056U, 40000L },
    { 425569U, 41000L },
    { 434072U, 42000L },
    { 442559U, 43000L },
    { 451027U, 44000L },
    { 459469U, 45000L },
    { 467882U, 46000L },
    { 476260U, 47000L },
    { 484599U, 48000L },
    { 492895U, 49000L },
    { 501144U, 50000L },
    { 509341U, 51000L },
    { 517483U, 52000L },
    { 525565U, 53000L },
    { 533585U, 54000L },
    { 541539U, 55000L },
    { 549424U, 56000L },
    { 557236U, 57000L },
    { 564973U, 58000L },
    { 572633U, 59000L },
    { 580212U, 60000L },
    { 587708U, 61000L },
    { 595120U, 62000L },
    { 602445U, 63000L },
    { 609681U, 64000L },
    { 616827U, 65000L },
    { 623881U, 66000L },
    { 630842U, 67000L },
    { 637708U, 68000L },
    { 644479U, 69000L },
    { 651154U, 70000L },
    { 657732U, 71000L },
    { 664212U, 72000L },
    { 670594U, 73000L },
    { 676877U, 74000L },
    { 683062U, 75000L },
    { 689147U, 76000L },
    { 695134U, 77000L },
    { 701022U, 78000L },
    { 706812U, 79000L },
    { 712503U, 80000L },
};

#endif /* USER_THERMISTOR_LUT_H */
